services:
  app:
    build: .
    env_file:
      - .env.docker
    volumes:
      - .:/usr/src/app
    command: sh ./entrypoint.sh
    container_name: deadlockBackend
    depends_on:
      - db
    environment:
      - DOCKER=true
    ports:
      - "${PORT}:${PORT}"
      - "51212:51212"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - deadlock_postgres_volume:/var/lib/postgresql/data

volumes:
  deadlock_postgres_volume: